version: '3.8'
services:
  signstash:
    image: "#{Docker.Internal.Registry}#/library/teammust/einvoice:integration-client-ws-b152"
    ports:
      - "#{Config.Signstash.ExternalPort}#:8080"
    command: >
      --einvoice-integration-client.service.domain="#{Config.Multicert.Stage}#"
      --einvoice-integration-client.rest.provider.proxy.hostname="#{Cofidis.Proxy.Hostname}#"
      --einvoice-integration-client.rest.provider.proxy.port="#{Cofidis.Proxy.Port}#"
      --einvoice-integration-client.scheduler.task.processHotFoldersByDocumentThreshold.cron-expression="0 0/10 * * * ?"
      --einvoice-integration-client.hot.folder.documents.processing.threshold="#{Config.Multicert.Treshold}#"
      --hot.folder.enabled=TRUE
    volumes:
      - /mnt/sct_factcofidis_signstash/db:/tmp
      - /mnt/sct_factcofidis_signstash/config/client-services-config.json:/home/client-services-config.json
      - /mnt/sct_factcofidis_signstash/sign:/home/sign
    deploy:
      resources:
        limits:
          memory: 4g
    #restart: unless-stopped

  minio:
    image: "#{Docker.Internal.Registry}#/library/minio:20240817"
    command: [ "server", "/storage", "--console-address", ":9001" ]
    environment:
      MINIO_ROOT_USER: "#{Config.Minio.Root.User}#"
      MINIO_ROOT_PASSWORD: "#{Config.Minio.Root.Password}#"
    ports:
      - "#{Config.Minio.Port}#:9001"
      - "#{Config.Minio.Port.Business}#:9000"
    volumes:
      - /mnt/sct_factcofidis_signstash/minio:/storage:delegated

  mc:
    image: "#{Docker.Internal.Registry}#/library/sct_factcofidis_signstash:#{Build.SourceBranchName}#-#{Build.BuildNumber}#"
    environment:
      MINIO_ALIAS: "minio"
      MINIO_ENDPOINT: "#{Config.Minio.Endpoint}#"
      MINIO_ACCESS_KEY: "#{Config.Minio.Login.User}#"
      MINIO_SECRET_KEY: "#{Config.Minio.Login.Password}#"
      MINIO_BUCKET_NAME: "storage"
      FOLDER_PATH_SYNC: "/home/sign"
      MAX_RETRIES: 5
      RETRY_DELAY: 10
    volumes:
      - /mnt/sct_factcofidis_signstash/sign:/home/sign
    depends_on:
      - signstash
      - minio
    deploy:
      mode: global
